---
kind: Service
apiVersion: v1
metadata:
  name: cynk8stest
spec:
  selector:
    app: cynk8stest
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cynk8stest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cynk8stest
  template:
    metadata:
      labels:
        app: cynk8stest
    spec:
      containers:
        - name: cynk8stest
          image: bitcynth/cynk8stest:latest
          ports:
            - containerPort: 8080
              protocol: TCP
