name: Deployment
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Login to docker registry
      uses: Azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: bitcynth
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build the Docker image
      run: |
        docker build . --build-arg build_version="${{ github.sha }}" --build-arg build_time=$(date +'%Y-%m-%d_%T') -t docker.pkg.github.com/bitcynth/cynk8stest/main:${{ github.sha }}
        docker push docker.pkg.github.com/bitcynth/cynk8stest/main:${{ github.sha }}
    
    - name: Set k8s context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Create k8s secret
      uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: docker.pkg.github.com
        container-registry-username: bitcynth
        container-registry-password: ${{ secrets.GITHUB_TOKEN }}
        secret-name: k8s-secret

    - name: Deploy k8s
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          manifests/deployment.yaml
          manifests/service.yaml
        images: |
          docker.pkg.github.com/bitcynth/cynk8stest/main:${{ github.sha }}